version: '3.1'

services:

  demoapp:
    build: .
    restart: on-failure
    ports:
      - "5001:8000"
    depends_on:
      - mariadb
    tty: true

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql